### ISSUE TITLE
Add travis testing

### ISSUE THREAD

**Issue by onnimonni** [k1sul1/custom-admin-notices#2]
Hey!

You can add travis testing by following this guide I wrote while working in Seravo:
https://seravo.fi/2015/continuous-integration-testing-for-wordpress-plugins-on-github-using-travis-ci

**Few examples**
You can also have a look for phpunit testing here:
https://github.com/devgeniem/wp-sanitize-accented-uploads/blob/master/.travis.yml

And just running php syntax checking in the project here:
https://github.com/devgeniem/better-wp-install-dropin/blob/master/.travis.yml

**Comment by k1sul1** [comment]
Looks reasonably easy. Thanks! 

I'll take a closer look in the near future.

**Comment by k1sul1** [comment]
Well that was surprisingly easy. Wonder why I haven't done that in the past. Seems that 5.2 & 5.3 are failing for whatever reason, but that will probably be easy to fix. 

I'm still not really digging into the concept of unit testing, and I don't even know what would I test in this kind of plugin that basically just glues existing functionality together. 

I mean I should probably learn how to test stuff and so on but I'm probably going to need a private lesson or something :D

**Comment by onnimonni** [comment]
I just usually add as many small functions as possible and test few different use cases ( different parameters for those functions ) and assert those use cases in unit tests.

Having a good test coverage needs your code to be structured in small testable pieces. This just needs an attitude shift and takes some time.

If you want to test wordpress integrations deeper you should use: https://github.com/10up/wp_mock 

I would want to start using those but have been too busy/lazy :(

**Comment by onnimonni** [comment]
It seems that php 5.3 & 5.2 can't run php as a server so you can't use the default tests from Seravo example.

I would just add different testing matrix for them and maybe for starters just syntax check those.

**Comment by k1sul1** [comment]
I'll dig around it sometime. 

I guess I could break some of the functions in the class into smaller portions & refactor the functions a bit, doesn't make a lot of sense including a script in checkBanners. Maybe I'll rename it to renderBanners and everyone is happy? :trollface:

**Comment by k1sul1** [comment]
Someday I will learn to write tests, but at this time I don't really have the time and/or patience to write them, at least for this project. Travis tests will do for now :)
